name: Auto-fix WPCS & CPCS (WP Plugin)

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_run:
    workflows: ["ClassicPress checks", "WPCS checks"]  # Your check workflows
    types: [completed]

jobs:
  phpcbf:
    name: PHPCBF Auto-fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: failure() || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PHPCS/PHPCBF WPCS + CPCS
        uses: shalior/wordpress-phpcs-action@master
        with:
          github_token: ${{ github.token }}
          phpcs_standard: WordPress,ClassicPress  # Both standards
          phpcs_args: '--ignore=*/vendor/*,*/node_modules/*'
          phpcbf_args: '--ignore=*/vendor/*,*/node_modules/*'

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: PHPCBF WPCS/CPCS auto-fixes [skip ci]'
          file_pattern: '*.php'
